// <auto-generated />
namespace G8.IPM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init_ipm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_ipm));
        
        string IMigrationMetadata.Id
        {
            get { return "201811050620266_init_ipm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
